### ISSUE TITLE
How to add my custom business logic?

### ISSUE THREAD

**Issue by mnlbox** [elitan/hasura-backend-plus#10]
Hi @elitan,
I want to add some business logic to my Hasura and see that this repo is good as a start point.
Can you guide me about how we can do this?
Are you any suggestion for me?
Are you any plan to simplify this use-case? (customized business logic)

**Comment by elitan** [comment]
This repo wont help you with that. I suggest you use something like [Zeit Now](https://zeit.co/now), [AWS Lambda](https://aws.amazon.com/lambda/) or similar.

**Comment by mnlbox** [comment]
Why?
Is it a back practice to create a new folder in https://github.com/elitan/hasura-backend-plus/tree/master/src and add custom business logic there? :thinking:

**Comment by MichaelJCole** [comment]
@mnlbox Yes, what I think @elitan is saying is you should fork the project and make your own.  Without a plugin system, HBP is more of a boilerplate than a complete service.

**Comment by plmercereau** [comment]
I think I disagree. HBP is meant to do two things, authentication and proxying S3 objects.
Depending on what you mean by business logic, I would rather consider using Hasura events, remote schemas or actions, and embrace more of a microservice architecture rather than expecting hbp should become a monolith.
If your missing business logic is related to storage or authentication, I suggest you open an issue so we can talk about it 😊
