### ISSUE TITLE
Split this project

### ISSUE THREAD

**Issue by RodolfoSilva** [elitan/hasura-backend-plus#32]
@elitan nice job with this library. 
I think we can split this project in two small projects. 
One for authentication only and one for storage only. What do you think of this approach?

And we can use the docker-compose to merge both with `hasrua/graphql-engine`.

Right now I started making [hasura-auth](https://github.com/RodolfoSilva/hasura-auth). And @toastedtoast has started [hasura-storage](https://github.com/toastedtoast/hasura-storage), both forked from HB+.

But I think we can unify all this projects in a organization with HB+ splited. 

What do you think?

cc\ @mnlbox

**Comment by elitan** [comment]
What is the benefit of splitting the project? Why not keep it as it is?

**Comment by RodolfoSilva** [comment]
Has use cases where we don't need both features. I think we can separate the concerns.

**Comment by mnlbox** [comment]
@RodolfoSilva I also agree because now many user use some other authentication solution like firebase or Auth0 and maybe just need storage part.
I agree about work under same organization because now Hasura has a lot of authentication server but I think none of them is ready for production with work as a community we can create one good solution.
Now I know this library and authentication server:
https://github.com/RodolfoSilva/hasura-auth
https://github.com/platyplus/authentication-server
https://github.com/platyplus/authentication-server

I also suggest to switch to more general solution like:
https://github.com/httpsOmkar/keycloak-hasura-connector
@httpsOmkar done a great work and I think with some docs and graphql wrapper all member in Hasura community can use that solution. Maybe it's better to make something like Keycloak as a first citizen in Hasura world :wink:

**Comment by elitan** [comment]
Would it not be easier to introduce an environment variable to deactivate auth/storage?

**Comment by mnlbox** [comment]
Related issue here: #13
I agree with this approach :wink:

**Comment by elitan** [comment]
Great!
