### ISSUE TITLE
JWT token in http only cookie

### ISSUE THREAD

**Issue by grgurev** [elitan/hasura-backend-plus#36]
I have a question regarding /login route. When server authenticates the user, http only cookie is created and sent to the client. I want to know why ? .. because Hasura in JWT mode cannot read JWT from cookie to create authorization header as explained [here](https://github.com/hasura/graphql-engine/issues/2183) 
Does this cookie have any other purpose?

**Comment by elitan** [comment]
Hi @grgurev 

That is an excellent question. The idea is that, when you login, you will save the jwt token in the client. Ex localStorage. This JWT token can be used when making request to Hasura.

The reason for the cookie is when you access files. Since the cookie is set, hasura-backend-plus will make sure you have the right privileges (in the storage-rules file) when you upload/download files.

Does that make sense?

For quicker chat response, you can join nhost.io (which uses hasura-backend-plus) discord server https://discord.gg/9V7Qb2U

**Comment by grgurev** [comment]
ahh ok everything's clear now I didn't look for a storage part of the HBP as I'm concentrated in auth part 😀 ..
