### ISSUE TITLE
Include documentation for migration when schema changes

### ISSUE THREAD

**Issue by frissonlabs** [elitan/hasura-backend-plus#59]
Any chance documentation for migration can be included when schema changes? I'm not sure what is the best way to do so with the additional of the oauth providers and I can see in db-init.sql that the schema has significant changes

**Comment by elitan** [comment]
Yes, there are significant changes in this next release. I'm my self trying to figure out what the best way to migrate is.

I think there will be a lot of manual work since, just changing user id from `int` to `uuid` is a big change. This will require your FKs to change too. And that means dropping and recreating the FKs, which in turn means for Hasura to retrack them. 

I do not think there is aa easy and general way to do this.

**Comment by elitan** [comment]
There is no quick fix.

What I ended up doing was dumping the whole database and carefully, and manually, re instantiate the database. 

1. Recreate the tables with the updated types
2. Make sure the FKs are correct
3. Insert data that is not relational or not depended on the new db update
4. Wrote a custom python script that loaded all data into memory and inserted it. Ex: 1. Insert user 2. get new user uuid. 3. Get all projects for that user. 4. Insert that users projects (with the updated uuid user_id) etc.

Hopefully this will be the last time we do such significant changes the the database structure. 🙏
